"""
Bangun dataset masakan Nusantara dengan nutrisi DASH lengkap.

Pendekatan:
- Gunakan data nutrisi per sajian standar dari referensi tepercaya:
  USDA FoodData Central, Indonesian Food Composition Database (IDDB),
  Paper akademis tentang nutrisi makanan Indonesia.
- Ukuran porsi (gram) merujuk pada porsi rata-rata orang Indonesia
  (Pedoman Gizi Seimbang Kemenkes 2014).
- Setiap entri ditandai is_estimated=True dengan source disebutkan.

OUTPUT:
- ml/artifacts/traditional_dishes.csv (dataset masakan jadi)
- Bisa di-merge dengan food_items_clean.csv saat training berikutnya
"""

import sys
from pathlib import Path

import pandas as pd

BACKEND = Path(__file__).resolve().parent.parent

# ─── Dataset Masakan Nusantara Populer ────────────────────────────────────────
# Format: per 100 gram porsi (consistent dengan TKPI)
# Sumber:
#  - USDA: USDA FoodData Central
#  - IDDB: Indonesian Food Composition Database (Kemenkes)
#  - Paper: Nutritional analysis dari paper-paper Indonesia
#  - Estimasi: dihitung dari komposisi resep × TKPI bahan
#
# Nilai natrium PENTING — banyak masakan Indonesia tinggi sodium
# karena penggunaan kecap, garam, dan terasi.

DISHES = [
    # ─── REGION: PADANG / SUMATERA BARAT ─────────────────────────────
    {
        "food_code": "ID-NU001",
        "name": "Rendang Sapi",
        "category": "Daging & Unggas",
        "region": "Sumatera Barat",
        "meal_type": "makan_siang",
        "energy_kcal": 200,
        "protein_g": 22.0,
        "fat_total_g": 11.0,
        "fat_saturated_g": 6.5,
        "carbs_g": 4.0,
        "fiber_g": 1.5,
        "sodium_mg": 480,    # tinggi karena bumbu + garam
        "potassium_mg": 290,
        "calcium_mg": 28,
        "magnesium_mg": 24,
        "phosphorus_mg": 165,
        "iron_mg": 2.8,
        "data_source": "Estimasi-USDA",
        "is_estimated": True,
        "reference": "USDA Beef in coconut sauce + Indonesian recipe",
    },
    {
        "food_code": "ID-NU002",
        "name": "Gulai Ayam",
        "category": "Daging & Unggas",
        "region": "Sumatera Barat",
        "meal_type": "makan_siang",
        "energy_kcal": 165,
        "protein_g": 14.5,
        "fat_total_g": 11.0,
        "fat_saturated_g": 6.0,
        "carbs_g": 3.0,
        "fiber_g": 0.8,
        "sodium_mg": 420,
        "potassium_mg": 240,
        "calcium_mg": 22,
        "magnesium_mg": 20,
        "phosphorus_mg": 145,
        "iron_mg": 1.5,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: ayam + santan + bumbu kuning",
    },
    {
        "food_code": "ID-NU003",
        "name": "Sate Ayam",
        "category": "Daging & Unggas",
        "region": "Sumatera Barat",
        "meal_type": "makan_siang",
        "energy_kcal": 188,
        "protein_g": 18.0,
        "fat_total_g": 9.5,
        "fat_saturated_g": 2.5,
        "carbs_g": 6.5,
        "fiber_g": 1.2,
        "sodium_mg": 520,    # kecap manis
        "potassium_mg": 220,
        "calcium_mg": 18,
        "magnesium_mg": 22,
        "phosphorus_mg": 145,
        "iron_mg": 1.4,
        "data_source": "Estimasi-USDA",
        "is_estimated": True,
        "reference": "USDA Chicken satay",
    },

    # ─── REGION: JAWA ────────────────────────────────────────────────
    {
        "food_code": "ID-NU010",
        "name": "Soto Ayam",
        "category": "Daging & Unggas",
        "region": "Jawa Tengah",
        "meal_type": "sarapan",
        "energy_kcal": 95,
        "protein_g": 8.5,
        "fat_total_g": 4.5,
        "fat_saturated_g": 1.2,
        "carbs_g": 5.5,
        "fiber_g": 0.8,
        "sodium_mg": 380,
        "potassium_mg": 195,
        "calcium_mg": 25,
        "magnesium_mg": 18,
        "phosphorus_mg": 105,
        "iron_mg": 1.0,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: ayam + soun + bumbu",
    },
    {
        "food_code": "ID-NU011",
        "name": "Gado-gado",
        "category": "Sayuran",
        "region": "Jakarta",
        "meal_type": "makan_siang",
        "energy_kcal": 137,
        "protein_g": 6.5,
        "fat_total_g": 7.0,
        "fat_saturated_g": 1.8,
        "carbs_g": 14.0,
        "fiber_g": 4.5,
        "sodium_mg": 260,
        "potassium_mg": 380,
        "calcium_mg": 75,
        "magnesium_mg": 45,
        "phosphorus_mg": 105,
        "iron_mg": 1.8,
        "data_source": "Eatthismuch + adjustment",
        "is_estimated": True,
        "reference": "EatThisMuch Indonesian Gado-gado Salad",
    },
    {
        "food_code": "ID-NU012",
        "name": "Pecel Sayur",
        "category": "Sayuran",
        "region": "Jawa Timur",
        "meal_type": "sarapan",
        "energy_kcal": 110,
        "protein_g": 5.5,
        "fat_total_g": 5.5,
        "fat_saturated_g": 1.0,
        "carbs_g": 12.0,
        "fiber_g": 5.2,
        "sodium_mg": 240,
        "potassium_mg": 410,
        "calcium_mg": 92,
        "magnesium_mg": 50,
        "phosphorus_mg": 95,
        "iron_mg": 2.0,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: bayam, kacang panjang, tauge, bumbu kacang",
    },
    {
        "food_code": "ID-NU013",
        "name": "Sayur Asem",
        "category": "Sayuran",
        "region": "Jawa Barat",
        "meal_type": "makan_siang",
        "energy_kcal": 35,
        "protein_g": 1.5,
        "fat_total_g": 0.6,
        "fat_saturated_g": 0.2,
        "carbs_g": 6.5,
        "fiber_g": 2.5,
        "sodium_mg": 220,
        "potassium_mg": 280,
        "calcium_mg": 38,
        "magnesium_mg": 22,
        "phosphorus_mg": 42,
        "iron_mg": 0.8,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: melinjo, kacang panjang, jagung, asam jawa",
    },
    {
        "food_code": "ID-NU014",
        "name": "Sayur Lodeh",
        "category": "Sayuran",
        "region": "Jawa",
        "meal_type": "makan_siang",
        "energy_kcal": 92,
        "protein_g": 3.5,
        "fat_total_g": 6.5,
        "fat_saturated_g": 4.0,
        "carbs_g": 6.0,
        "fiber_g": 2.8,
        "sodium_mg": 280,
        "potassium_mg": 295,
        "calcium_mg": 45,
        "magnesium_mg": 28,
        "phosphorus_mg": 60,
        "iron_mg": 1.0,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: santan + sayuran campur",
    },
    {
        "food_code": "ID-NU015",
        "name": "Rawon",
        "category": "Daging & Unggas",
        "region": "Jawa Timur",
        "meal_type": "makan_siang",
        "energy_kcal": 145,
        "protein_g": 14.0,
        "fat_total_g": 8.0,
        "fat_saturated_g": 3.2,
        "carbs_g": 4.5,
        "fiber_g": 1.0,
        "sodium_mg": 410,
        "potassium_mg": 280,
        "calcium_mg": 22,
        "magnesium_mg": 25,
        "phosphorus_mg": 130,
        "iron_mg": 2.2,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: daging sapi + kluwek + bumbu",
    },
    {
        "food_code": "ID-NU016",
        "name": "Nasi Uduk",
        "category": "Serealia",
        "region": "Jakarta",
        "meal_type": "sarapan",
        "energy_kcal": 175,
        "protein_g": 3.5,
        "fat_total_g": 5.5,
        "fat_saturated_g": 4.0,
        "carbs_g": 28.5,
        "fiber_g": 0.8,
        "sodium_mg": 220,
        "potassium_mg": 95,
        "calcium_mg": 12,
        "magnesium_mg": 18,
        "phosphorus_mg": 55,
        "iron_mg": 0.6,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: beras + santan",
    },

    # ─── REGION: BETAWI / JAKARTA ────────────────────────────────────
    {
        "food_code": "ID-NU020",
        "name": "Soto Betawi",
        "category": "Daging & Unggas",
        "region": "Jakarta",
        "meal_type": "makan_siang",
        "energy_kcal": 135,
        "protein_g": 9.5,
        "fat_total_g": 8.8,
        "fat_saturated_g": 5.0,
        "carbs_g": 4.5,
        "fiber_g": 0.6,
        "sodium_mg": 460,
        "potassium_mg": 220,
        "calcium_mg": 35,
        "magnesium_mg": 18,
        "phosphorus_mg": 110,
        "iron_mg": 1.5,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: daging sapi + santan + susu",
    },
    {
        "food_code": "ID-NU021",
        "name": "Ketoprak",
        "category": "Sayuran",
        "region": "Jakarta",
        "meal_type": "makan_siang",
        "energy_kcal": 155,
        "protein_g": 7.0,
        "fat_total_g": 7.0,
        "fat_saturated_g": 1.5,
        "carbs_g": 18.0,
        "fiber_g": 3.0,
        "sodium_mg": 320,
        "potassium_mg": 240,
        "calcium_mg": 95,
        "magnesium_mg": 35,
        "phosphorus_mg": 120,
        "iron_mg": 1.5,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: tauge, ketupat, tahu, bihun, bumbu kacang",
    },

    # ─── REGION: SUNDA / JAWA BARAT ──────────────────────────────────
    {
        "food_code": "ID-NU030",
        "name": "Karedok",
        "category": "Sayuran",
        "region": "Jawa Barat",
        "meal_type": "makan_siang",
        "energy_kcal": 120,
        "protein_g": 5.5,
        "fat_total_g": 6.5,
        "fat_saturated_g": 1.2,
        "carbs_g": 12.0,
        "fiber_g": 4.5,
        "sodium_mg": 180,
        "potassium_mg": 360,
        "calcium_mg": 65,
        "magnesium_mg": 38,
        "phosphorus_mg": 88,
        "iron_mg": 1.5,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: sayuran mentah + bumbu kacang",
    },
    {
        "food_code": "ID-NU031",
        "name": "Pepes Ikan",
        "category": "Ikan, Kerang & Udang",
        "region": "Jawa Barat",
        "meal_type": "makan_siang",
        "energy_kcal": 120,
        "protein_g": 18.0,
        "fat_total_g": 4.5,
        "fat_saturated_g": 1.0,
        "carbs_g": 2.0,
        "fiber_g": 0.5,
        "sodium_mg": 280,
        "potassium_mg": 320,
        "calcium_mg": 35,
        "magnesium_mg": 30,
        "phosphorus_mg": 200,
        "iron_mg": 1.0,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: ikan + bumbu, dibungkus daun pisang",
    },

    # ─── REGION: SULAWESI / BUGIS ────────────────────────────────────
    {
        "food_code": "ID-NU040",
        "name": "Coto Makassar",
        "category": "Daging & Unggas",
        "region": "Sulawesi Selatan",
        "meal_type": "makan_siang",
        "energy_kcal": 158,
        "protein_g": 12.5,
        "fat_total_g": 9.5,
        "fat_saturated_g": 3.5,
        "carbs_g": 4.0,
        "fiber_g": 0.8,
        "sodium_mg": 450,
        "potassium_mg": 260,
        "calcium_mg": 28,
        "magnesium_mg": 22,
        "phosphorus_mg": 145,
        "iron_mg": 2.0,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: daging sapi + jeroan + bumbu",
    },
    {
        "food_code": "ID-NU041",
        "name": "Konro",
        "category": "Daging & Unggas",
        "region": "Sulawesi Selatan",
        "meal_type": "makan_siang",
        "energy_kcal": 175,
        "protein_g": 14.0,
        "fat_total_g": 11.5,
        "fat_saturated_g": 4.5,
        "carbs_g": 3.5,
        "fiber_g": 0.5,
        "sodium_mg": 420,
        "potassium_mg": 240,
        "calcium_mg": 25,
        "magnesium_mg": 20,
        "phosphorus_mg": 165,
        "iron_mg": 2.4,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: iga sapi + bumbu hitam",
    },

    # ─── REGION: BATAK / SUMATERA UTARA ──────────────────────────────
    {
        "food_code": "ID-NU050",
        "name": "Saksang",
        "category": "Daging & Unggas",
        "region": "Sumatera Utara",
        "meal_type": "makan_siang",
        "energy_kcal": 195,
        "protein_g": 16.0,
        "fat_total_g": 12.5,
        "fat_saturated_g": 4.5,
        "carbs_g": 4.5,
        "fiber_g": 1.0,
        "sodium_mg": 380,
        "potassium_mg": 280,
        "calcium_mg": 22,
        "magnesium_mg": 24,
        "phosphorus_mg": 155,
        "iron_mg": 2.5,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: daging + andaliman + bumbu",
    },
    {
        "food_code": "ID-NU051",
        "name": "Arsik Ikan Mas",
        "category": "Ikan, Kerang & Udang",
        "region": "Sumatera Utara",
        "meal_type": "makan_siang",
        "energy_kcal": 130,
        "protein_g": 17.0,
        "fat_total_g": 5.5,
        "fat_saturated_g": 1.2,
        "carbs_g": 2.5,
        "fiber_g": 0.8,
        "sodium_mg": 320,
        "potassium_mg": 340,
        "calcium_mg": 38,
        "magnesium_mg": 32,
        "phosphorus_mg": 220,
        "iron_mg": 1.2,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: ikan mas + andaliman + asam",
    },

    # ─── REGION: MANADO ──────────────────────────────────────────────
    {
        "food_code": "ID-NU060",
        "name": "Tinutuan (Bubur Manado)",
        "category": "Sayuran",
        "region": "Sulawesi Utara",
        "meal_type": "sarapan",
        "energy_kcal": 78,
        "protein_g": 2.0,
        "fat_total_g": 0.5,
        "fat_saturated_g": 0.1,
        "carbs_g": 16.0,
        "fiber_g": 2.5,
        "sodium_mg": 145,
        "potassium_mg": 280,
        "calcium_mg": 35,
        "magnesium_mg": 28,
        "phosphorus_mg": 55,
        "iron_mg": 1.2,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: bubur + jagung + sayuran",
    },

    # ─── REGION: PAPUA ───────────────────────────────────────────────
    {
        "food_code": "ID-NU070",
        "name": "Papeda Ikan Kuah Kuning",
        "category": "Ikan, Kerang & Udang",
        "region": "Papua",
        "meal_type": "makan_siang",
        "energy_kcal": 105,
        "protein_g": 8.5,
        "fat_total_g": 2.5,
        "fat_saturated_g": 0.5,
        "carbs_g": 12.5,
        "fiber_g": 0.8,
        "sodium_mg": 280,
        "potassium_mg": 250,
        "calcium_mg": 28,
        "magnesium_mg": 25,
        "phosphorus_mg": 120,
        "iron_mg": 0.8,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: papeda sagu + ikan + kunyit",
    },

    # ─── HIDANGAN POPULER LAINNYA ────────────────────────────────────
    {
        "food_code": "ID-NU080",
        "name": "Nasi Goreng",
        "category": "Serealia",
        "region": "Nasional",
        "meal_type": "sarapan",
        "energy_kcal": 195,
        "protein_g": 5.5,
        "fat_total_g": 6.5,
        "fat_saturated_g": 1.5,
        "carbs_g": 28.0,
        "fiber_g": 1.2,
        "sodium_mg": 480,    # kecap + garam
        "potassium_mg": 130,
        "calcium_mg": 18,
        "magnesium_mg": 20,
        "phosphorus_mg": 75,
        "iron_mg": 1.0,
        "data_source": "USDA",
        "is_estimated": True,
        "reference": "USDA Indonesian fried rice",
    },
    {
        "food_code": "ID-NU081",
        "name": "Mie Goreng",
        "category": "Serealia",
        "region": "Nasional",
        "meal_type": "makan_siang",
        "energy_kcal": 215,
        "protein_g": 6.5,
        "fat_total_g": 8.0,
        "fat_saturated_g": 2.0,
        "carbs_g": 30.0,
        "fiber_g": 1.5,
        "sodium_mg": 520,
        "potassium_mg": 140,
        "calcium_mg": 22,
        "magnesium_mg": 25,
        "phosphorus_mg": 95,
        "iron_mg": 1.5,
        "data_source": "USDA",
        "is_estimated": True,
        "reference": "USDA Indonesian fried noodles",
    },
    {
        "food_code": "ID-NU082",
        "name": "Bakso Sapi",
        "category": "Daging & Unggas",
        "region": "Nasional",
        "meal_type": "makan_siang",
        "energy_kcal": 115,
        "protein_g": 9.0,
        "fat_total_g": 6.0,
        "fat_saturated_g": 2.5,
        "carbs_g": 6.5,
        "fiber_g": 0.8,
        "sodium_mg": 580,    # tinggi karena kuah + bakso
        "potassium_mg": 175,
        "calcium_mg": 22,
        "magnesium_mg": 18,
        "phosphorus_mg": 110,
        "iron_mg": 1.4,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: bakso daging sapi + mie + kuah kaldu",
    },
    {
        "food_code": "ID-NU083",
        "name": "Ayam Goreng Lengkuas",
        "category": "Daging & Unggas",
        "region": "Nasional",
        "meal_type": "makan_siang",
        "energy_kcal": 215,
        "protein_g": 22.0,
        "fat_total_g": 13.0,
        "fat_saturated_g": 3.5,
        "carbs_g": 2.5,
        "fiber_g": 0.5,
        "sodium_mg": 380,
        "potassium_mg": 230,
        "calcium_mg": 18,
        "magnesium_mg": 22,
        "phosphorus_mg": 175,
        "iron_mg": 1.4,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: ayam + bumbu lengkuas, digoreng",
    },
    {
        "food_code": "ID-NU084",
        "name": "Tempe Goreng",
        "category": "Kacang & Biji",
        "region": "Nasional",
        "meal_type": "lauk",
        "energy_kcal": 200,
        "protein_g": 17.0,
        "fat_total_g": 10.5,
        "fat_saturated_g": 1.5,
        "carbs_g": 12.0,
        "fiber_g": 5.5,
        "sodium_mg": 95,
        "potassium_mg": 295,
        "calcium_mg": 145,
        "magnesium_mg": 75,
        "phosphorus_mg": 220,
        "iron_mg": 2.5,
        "data_source": "USDA",
        "is_estimated": True,
        "reference": "USDA Tempeh, fried",
    },
    {
        "food_code": "ID-NU085",
        "name": "Tahu Bacem",
        "category": "Kacang & Biji",
        "region": "Jawa",
        "meal_type": "lauk",
        "energy_kcal": 165,
        "protein_g": 14.0,
        "fat_total_g": 8.0,
        "fat_saturated_g": 1.2,
        "carbs_g": 9.0,
        "fiber_g": 2.0,
        "sodium_mg": 320,
        "potassium_mg": 175,
        "calcium_mg": 285,
        "magnesium_mg": 38,
        "phosphorus_mg": 165,
        "iron_mg": 2.0,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: tahu + kecap manis + bumbu bacem",
    },
    {
        "food_code": "ID-NU086",
        "name": "Ikan Bakar Bumbu Kecap",
        "category": "Ikan, Kerang & Udang",
        "region": "Nasional",
        "meal_type": "makan_siang",
        "energy_kcal": 145,
        "protein_g": 22.0,
        "fat_total_g": 5.0,
        "fat_saturated_g": 1.0,
        "carbs_g": 3.5,
        "fiber_g": 0.5,
        "sodium_mg": 320,
        "potassium_mg": 380,
        "calcium_mg": 25,
        "magnesium_mg": 32,
        "phosphorus_mg": 245,
        "iron_mg": 1.0,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: ikan kakap/nila + bumbu kecap, dibakar",
    },
    {
        "food_code": "ID-NU087",
        "name": "Capcay Sayur",
        "category": "Sayuran",
        "region": "Nasional",
        "meal_type": "makan_siang",
        "energy_kcal": 65,
        "protein_g": 3.0,
        "fat_total_g": 2.5,
        "fat_saturated_g": 0.5,
        "carbs_g": 9.0,
        "fiber_g": 3.5,
        "sodium_mg": 280,
        "potassium_mg": 320,
        "calcium_mg": 75,
        "magnesium_mg": 28,
        "phosphorus_mg": 65,
        "iron_mg": 1.2,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: aneka sayuran + bawang putih",
    },
    {
        "food_code": "ID-NU088",
        "name": "Tumis Kangkung",
        "category": "Sayuran",
        "region": "Nasional",
        "meal_type": "makan_siang",
        "energy_kcal": 55,
        "protein_g": 2.5,
        "fat_total_g": 2.5,
        "fat_saturated_g": 0.4,
        "carbs_g": 6.5,
        "fiber_g": 3.0,
        "sodium_mg": 240,
        "potassium_mg": 380,
        "calcium_mg": 105,
        "magnesium_mg": 35,
        "phosphorus_mg": 50,
        "iron_mg": 2.0,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: kangkung + bawang + saus",
    },
    {
        "food_code": "ID-NU089",
        "name": "Telur Balado",
        "category": "Telur",
        "region": "Nasional",
        "meal_type": "lauk",
        "energy_kcal": 175,
        "protein_g": 11.0,
        "fat_total_g": 12.0,
        "fat_saturated_g": 3.0,
        "carbs_g": 5.5,
        "fiber_g": 1.5,
        "sodium_mg": 380,
        "potassium_mg": 195,
        "calcium_mg": 55,
        "magnesium_mg": 18,
        "phosphorus_mg": 165,
        "iron_mg": 1.8,
        "data_source": "Estimasi",
        "is_estimated": True,
        "reference": "Decomposition: telur + bumbu balado (cabai)",
    },
]


def main():
    out_path = BACKEND / "ml" / "artifacts" / "traditional_dishes.csv"

    df = pd.DataFrame(DISHES)

    print(f"Total masakan: {len(df)}")
    print(f"\nDistribusi region:")
    print(df["region"].value_counts())
    print(f"\nDistribusi kategori:")
    print(df["category"].value_counts())

    print(f"\nStatistik nutrisi (per 100g):")
    nutrient_cols = ["sodium_mg", "potassium_mg", "calcium_mg", "fiber_g", "fat_total_g"]
    print(df[nutrient_cols].describe())

    # Hitung DASH score
    sys.path.insert(0, str(BACKEND))
    from services.dash_score_service import calculate_dash_score, get_dash_category
    from services.nutrition_calculator import calculate_personal_targets

    targets = calculate_personal_targets("laki-laki", 70, 170, 35, [])
    df["dash_score"] = df.apply(
        lambda r: calculate_dash_score(
            {
                "sodium_mg": r["sodium_mg"],
                "potassium_mg": r["potassium_mg"],
                "calcium_mg": r["calcium_mg"],
                "fiber_g": r["fiber_g"],
                "fat_total_g": r["fat_total_g"],
            },
            targets,
        ),
        axis=1,
    )
    df["dash_category"] = df["dash_score"].apply(get_dash_category)

    df.to_csv(out_path, index=False)
    print(f"\nTersimpan: {out_path}")

    print(f"\nDistribusi DASH:")
    print(df["dash_category"].value_counts())

    print(f"\nTop 5 masakan terbaik (DASH score):")
    top = df.nlargest(5, "dash_score")[["name", "region", "dash_score", "sodium_mg", "potassium_mg"]]
    print(top.to_string(index=False))

    print(f"\nMasakan yang perlu perhatian (DASH < 40):")
    low = df[df["dash_score"] < 40][["name", "region", "dash_score", "sodium_mg", "fat_total_g"]]
    print(low.to_string(index=False))


if __name__ == "__main__":
    main()
